# Generated by Django 6.0.2 on 2026-02-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(default='Sin nombre', max_length=200, verbose_name='Nombre'),
        ),
    ]
